### ISSUE TITLE
Question about second QP optimization

### ISSUE THREAD

**Issue by feiyuxiaoThu** [purewater0901/obstacle_velocity_planner#1]
Thanks for your code, and I have a small question.
First, you formulate a QP problem in S-T domin,  and then you use the output of the first stage to formulate the second QP problem in V-S domin. But what is the reason for the second stage?  I cannot understand the improvement in the second stage compared to the first stage.
And you add cost function for $j_{related}$, $a_{related}$ in the second stage while this terms already exist in the constraints in hard form.
Thanks for your reply.

**Comment by purewater0901** [comment]
@feiyuxiaoThu Thank you for your comment. In the first stage, we just do the optimization for computing rough speed profiles. Since it is hard to get position-wise speed constraints with S-T domain speed optimization, we added second-stage QP optimization. By solving S-T domain QP optimization in the second stage, we can get smooth speed profile with position-wise speed constraint.
